import type { NextPage } from 'next';
import Head from 'next/head';

// external services
import { firebaseAuth } from 'src/services/firebase/firebaseClient';
import { signInWithEmailAndPassword } from 'firebase/auth';

// external components
import { Form, Input, Button } from 'antd';

// styles
import styles from 'src/styles/Home.module.scss';
import 'antd/dist/antd.css';

const Home: NextPage = () => {
  const handleLogin = async (loginParams: any) => {
    const { username, password } = loginParams;

    try {
      const response = await signInWithEmailAndPassword(
        firebaseAuth,
        username,
        password
      );

      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  const handleSucessInput = async (loginInput: any) => {
    const { username, password } = loginInput;
    const loginParams = {
      username,
      password,
    };

    await handleLogin(loginParams);
  };

  const handleFailedInput = (errorInfo: any) => {
    console.log('Failed:', errorInfo);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>ServerSide Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Form
          name="basic"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          initialValues={{ remember: true }}
          onFinish={handleSucessInput}
          onFinishFailed={handleFailedInput}
          autoComplete="off"
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[{ required: true, message: 'Please input your username!' }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: 'Please input your password!' }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>
      </main>
    </div>
  );
};

export default Home;
